# 01 — Database Exploration

## Objective
Understand the Northwind database schema — what tables exist, 
how they relate to each other, and what business questions 
we can answer with this data.

## Contents
1. Connect to the database
2. Explore available tables
3. Inspect key tables
4. Define business questions

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../data/northwind.db')
print("Connected successfully")

Connected successfully

In [2]:
query = "SELECT name FROM sqlite_master WHERE type='table'"
tables = pd.read_sql(query, conn)
print(tables)

                    name
0             Categories
1        sqlite_sequence
2   CustomerCustomerDemo
3   CustomerDemographics
4              Customers
5              Employees
6    EmployeeTerritories
7          Order Details
8                 Orders
9               Products
10               Regions
11              Shippers
12             Suppliers
13           Territories

In [3]:
def inspect_table(table_name):
    query = f"PRAGMA table_info('{table_name}')"
    return pd.read_sql(query, conn)

inspect_table('Orders')

    cid            name      type  notnull dflt_value  pk
0     0         OrderID   INTEGER        1        NaN   1
1     1      CustomerID      TEXT        0        NaN   0
2     2      EmployeeID   INTEGER        0        NaN   0
3     3       OrderDate  DATETIME        0        NaN   0
4     4    RequiredDate  DATETIME        0        NaN   0
5     5     ShippedDate  DATETIME        0        NaN   0
6     6         ShipVia   INTEGER        0        NaN   0
7     7         Freight   NUMERIC        0          0   0
8     8        ShipName      TEXT        0        NaN   0
9     9     ShipAddress      TEXT        0        NaN   0
10   10        ShipCity      TEXT        0        NaN   0
11   11      ShipRegion      TEXT        0        NaN   0
12   12  ShipPostalCode      TEXT        0        NaN   0
13   13     ShipCountry      TEXT        0        NaN   0

In [4]:
inspect_table('Order Details')

   cid       name     type  notnull dflt_value  pk
0    0    OrderID  INTEGER        1        NaN   1
1    1  ProductID  INTEGER        1        NaN   2
2    2  UnitPrice  NUMERIC        1          0   0
3    3   Quantity  INTEGER        1          1   0
4    4   Discount     REAL        1          0   0

In [5]:
inspect_table('Products')

   cid             name     type  notnull dflt_value  pk
0    0        ProductID  INTEGER        1        NaN   1
1    1      ProductName     TEXT        1        NaN   0
2    2       SupplierID  INTEGER        0        NaN   0
3    3       CategoryID  INTEGER        0        NaN   0
4    4  QuantityPerUnit     TEXT        0        NaN   0
5    5        UnitPrice  NUMERIC        0          0   0
6    6     UnitsInStock  INTEGER        0          0   0
7    7     UnitsOnOrder  INTEGER        0          0   0
8    8     ReorderLevel  INTEGER        0          0   0
9    9     Discontinued     TEXT        1        '0'   0